// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9n9n6ukHnNxO4RDlzuoXdQEus568oOB0',
    appId: '1:965419413061:web:ba0bb494b167c8e99c3d2c',
    messagingSenderId: '965419413061',
    projectId: 'active-commuter-system-b0b31',
    authDomain: 'active-commuter-system-b0b31.firebaseapp.com',
    storageBucket: 'active-commuter-system-b0b31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvrVzwa76vsc5HV228wvOEsIumrno56w',
    appId: '1:965419413061:android:e0b24449b5363cfe9c3d2c',
    messagingSenderId: '965419413061',
    projectId: 'active-commuter-system-b0b31',
    storageBucket: 'active-commuter-system-b0b31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJiTd43Kv1qgzKmWMtpx8GOAzvPUDb7Po',
    appId: '1:965419413061:ios:5bda8c7914c057669c3d2c',
    messagingSenderId: '965419413061',
    projectId: 'active-commuter-system-b0b31',
    storageBucket: 'active-commuter-system-b0b31.firebasestorage.app',
    iosBundleId: 'com.example.activeCommuterSupport',
  );

}